fix bug

diff --git a/.github/workflows/package.windows.yml b/.github/workflows/package.windows.yml
--- a/.github/workflows/package.windows.yml
+++ b/.github/workflows/package.windows.yml
@@ -129,6 +129,61 @@ jobs:
 
           Get-ChildItem -Path .\build -Recurse | Select-Object FullName | Write-Host
 
+      - name: SignPath installer
+        shell: pwsh
+        run: |
+          if (${{ github.event.inputs.sign-file }} -eq 'true') {
+          
+            if (-not (Get-Module -ListAvailable -Name SignPath)) {
+              Install-Module -Name SignPath -Force -Scope CurrentUser
+              Write-Host "SignPath module installed"
+            }
+          
+            Import-Module SignPath -Force
+            Write-Host "SignPath module imported"
+        
+            # Указываем файлы для подписи
+            $filesToSign = @(
+              "portable/build/wunjo/windows/src/libcrypto-1_1.dll",
+              "portable/build/wunjo/windows/src/libssl-1_1.dll",
+              "portable/build/wunjo/windows/src/libffi-7.dll",
+              "portable/build/wunjo/windows/src/vcruntime140.dll",
+              "portable/build/wunjo/windows/src/vcruntime140_1.dll",
+              "portable/build/wunjo/windows/src/Wunjo.exe",
+              "portable/build/wunjo/windows/src/app/win/webgui.exe"
+            )
+        
+            foreach ($file in $filesToSign) {
+              if (Test-Path $file) {
+                Write-Host "File for signature: $file"
+                $signedPath = "$($file.DirectoryName)\signed_$($file.Name)"
+        
+                try {
+                  Submit-SigningRequest -InputArtifactPath $file -ApiToken "${{ secrets.SIGN_PATH_TOKEN }}" `
+                    -OrganizationId "b01997fa-53cc-4ead-afd5-d225dccbc2c9" `
+                    -ProjectSlug "wunjo.wladradchenko.ru" `
+                    -SigningPolicySlug "test-signing" `
+                    -OutputArtifactPath "$signedPath" -WaitForCompletion
+        
+                  if (Test-Path $signedPath) {
+                    Remove-Item -Path $file
+                    Rename-Item -Path $signedPath -NewName $file.Name
+                    Write-Host "The file '$file' has been signed and replaced."
+                  } else {
+                    Write-Error "Signing Error! The signed file '$file' was not created."
+                    exit 1
+                  }
+                } catch {
+                  Write-Error "Signing failed for '$file': $_"
+                  exit 1
+                }
+              } else {
+                Write-Error "File '$file' not found!"
+                exit 1
+              }
+            }
+          }
+
       - name: Package application
         shell: pwsh
         run: |
@@ -140,57 +195,6 @@ jobs:
           $distFiles = Get-ChildItem -Path .\dist
           Write-Host "Created package files:"
           $distFiles | ForEach-Object { Write-Host $_.FullName }
-
-      - name: SignPath installer
-        shell: pwsh
-        run: |
-          if (${{ github.event.inputs.sign-file }} -eq 'true') {
-          
-            if (-not (Get-Module -ListAvailable -Name SignPath)) {
-                Install-Module -Name SignPath -Force -Scope CurrentUser
-                Write-Host "SignPath module installed"
-            }
-            
-            Import-Module SignPath -Force
-            Write-Host "SignPath module imported"
-            
-            cd portable/dist
-  
-            # Get path to MSI or ZIP file (dynamically)
-            $artifact = Get-ChildItem -File | Where-Object { $_.Extension -in ".msi", ".zip" } | Select-Object -First 1
-  
-            if (-not $artifact) {
-                Write-Error "MSI or ZIP file not found in dist folder!"
-                exit 1
-            }
-  
-            Write-Host "File for signature: $($artifact.FullName)"
-  
-            $signedPath = "$($artifact.DirectoryName)\signed_$($artifact.Name)"
-  
-            try {
-              Submit-SigningRequest `
-                -InputArtifactPath $artifact.FullName `
-                -ApiToken "${{ secrets.SIGN_PATH_TOKEN }}" `
-                -OrganizationId "b01997fa-53cc-4ead-afd5-d225dccbc2c9" `
-                -ProjectSlug "wunjo.wladradchenko.ru" `
-                -SigningPolicySlug "test-signing" `
-                -OutputArtifactPath "$signedPath" `
-                -WaitForCompletion
-            
-              if (Test-Path $signedPath) {
-                Remove-Item -Path $artifact.FullName
-                Rename-Item -Path "$($artifact.DirectoryName)\signed_$($artifact.Name)" -NewName $artifact.Name
-                Write-Host "The file has been signed and replaced."
-              } else {
-                Write-Error "Signature Error! The signed file was not created."
-                exit 1
-              }
-            } catch {
-              Write-Error "Signing failed: $_"
-              exit 1
-            }
-          }
 
       - name: Upload Log
         if: failure()
